version: '3.8'
services:
  logFlowDB:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zayn.malik1
      POSTGRES_DB: logFlowDb
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zayn.malik1
      POSTGRES_DB: logFlowDbTest
    networks:
      - freecodecamp
networks:
  freecodecamp:
    
